<a href="https://colab.research.google.com/github/kartikmane45/physics_wallah_skills_assignments/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### THEORY QUESTIONS

 1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

Ans: NumPy is crucial for scientific computing and data analysis as it allows efficient numerical operations on large, multi-dimensional arrays and matrices. It enhances Python by:

Efficient Memory Usage: Consumes less memory than lists.
Vectorized Operations: Speeds up calculations by removing the need for loops.
Multi-dimensional Arrays: Supports complex data like matrices and tensors.
Comprehensive Functions: Provides a wide range of mathematical tools.
With optimized C code, NumPy significantly boosts Python’s speed for numerical tasks and makes data manipulation more intuitive using advanced indexing and slicing.

2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?


Ans:Both `np.mean()` and `np.average()` calculate the average of array elements in NumPy. The key difference is that `np.mean()` computes a simple arithmetic mean, while `np.average()` can compute a weighted average if weights are provided; otherwise, it behaves like `np.mean()`. You would use `np.mean()` for straightforward averages and `np.average()` when you need to account for weights in your calculation.


3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.

Ans:
To reverse a NumPy array along different axes, you can use slicing or the np.flip() function. For a 1D array, reverse it using slicing (arr[::-1]). For a 2D array, use np.flip() to reverse along specific axes, such as rows or columns.

Examples:


In [ ]:
# Examples:

# 1D Array
arr = np.array([1, 2, 3])
reversed_arr = arr[::-1]

# 2D Array (reverse along rows)
arr = np.array([[1, 2], [3, 4]])
reversed_arr = np.flip(arr, axis=0)

# 2D Array (reverse along columns)
reversed_arr = np.flip(arr, axis=1)


4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.

Ans:

To determine the data type of elements in a NumPy array, use the .dtype attribute (e.g., arr.dtype).

Data types are important for memory management and performance; different types consume varying amounts of memory and affect computation speed. For instance, using int32 (4 bytes) instead of float64 (8 bytes) can reduce memory usage significantly. Properly managing data types enhances efficiency and accelerates numerical operations in NumPy.

5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?
Ans:
**Ndarrays** (n-dimensional arrays) in NumPy are powerful data structures designed for efficient data storage and manipulation. Key features include:

**Homogeneous Data Type:** All elements must be of the same type.

**Multi-dimensionality:** Supports various dimensions (1D, 2D, 3D, etc.).

**Contiguous Memory Allocation:** Enhances speed and efficiency.

**Vectorized Operations:** Allows fast mathematical computations on entire arrays.

**Differences from Standard Python Lists:**
- Ndarrays require homogeneous data types, while lists can hold mixed types.

- Ndarrays are more memory-efficient and faster for numerical operations.

- Ndarrays support multi-dimensional data natively, whereas lists need nested structures for similar functionality.

6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.
Ans:

NumPy arrays outperform Python lists in large-scale numerical operations due to:

1. **Memory Efficiency:** Contiguous memory allocation reduces overhead.

2. **Faster Computation:** C-based implementations speed up calculations.

3. **Vectorization:** Enables batch processing without loops.

4. **Reduced Overhead:** Minimizes function call overhead.

These advantages lead to faster and more efficient handling of large datasets.

7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.
Ans:
vstack(): This function stacks arrays vertically (row-wise). It takes a tuple of arrays as input and combines them along a new vertical axis. All arrays must have the same number of columns.

hstack(): This function stacks arrays horizontally (column-wise). It also takes a tuple of arrays as input and combines them along a new horizontal axis. All arrays must have the same number of rows.

In [ ]:
import numpy as np

# Create two arrays
a = np.array([[1, 2], [3, 4]])  # 2x2 array
b = np.array([[5, 6]])           # 1x2 array

# Using vstack() to stack arrays vertically
vstack_result = np.vstack((a, b))
print("vstack result:\n", vstack_result)

# Using hstack() to stack arrays horizontally
hstack_result = np.hstack((a, b.T))  # Transpose b to match dimensions
print("hstack result:\n", hstack_result)


8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions
Ans:

np.fliplr() (Flip Left to Right)
Purpose: fliplr() reverses the columns of a 2D array, effectively flipping it horizontally (left to right).
Dimensional Requirement: The input array must be at least 2D. It flips along the second axis (axis=1).
Effect: The elements in each row are reversed, while the rows themselves remain in the same order.



In [ ]:
import numpy as np

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Flip the array left to right (horizontally)
result_fliplr = np.fliplr(arr_2d)
print(result_fliplr)


np.flipud() (Flip Up to Down)
Purpose: flipud() reverses the rows of a 2D array, effectively flipping it vertically (up to down).
Dimensional Requirement: flipud() works on arrays of any dimension (1D, 2D, etc.). It flips along the first axis (axis=0).
Effect: The rows of the array are reversed, while the columns remain in the same order.

In [ ]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Flip the array up to down (vertically)
result_flipud = np.flipud(arr_2d)
print(result_flipud)


9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

Ans:

The array_split() method in NumPy is used to split an array into multiple sub-arrays. Unlike the split() method, which requires the input array to be evenly divisible by the number of splits, array_split() can handle uneven splits, making it more flexible

Key Features of array_split():
Input Array: It works with arrays of any dimensionality (1D, 2D, 3D, etc.).
Number of Splits: You can specify the number of sub-arrays you want to create.

Handling Uneven Splits:
When the number of elements in the array is not evenly divisible by the number of splits, array_split() distributes the extra elements to the earlier sub-arrays. The sub-arrays are created such that their sizes differ by at most 1 element.

10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?
Ans:

Vectorization in NumPy refers to the process of performing operations on entire arrays rather than using explicit loops. This allows NumPy to leverage low-level optimizations and take advantage of parallel processing, leading to faster computations.

Broadcasting is a technique that allows NumPy to perform arithmetic operations on arrays of different shapes. It automatically expands the smaller array along the dimensions of the larger one to make their shapes compatible for element-wise operations.

Together, vectorization and broadcasting enable efficient array operations by:

Reducing the need for loops, resulting in cleaner and more readable code.
Leveraging optimized C and Fortran libraries, which significantly enhances performance.
Allowing operations on arrays of varying sizes without manual reshaping, simplifying code development.
This leads to faster execution times and more efficient memory usage in numerical computations.

### PRACTICAL QUESTIONS

In [ ]:
#1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.
import numpy as np
a=np.random.randint(1,100 , size = (3,3))
print(a)

[[84 18  3]
 [49 72 61]
 [34  7 64]]


In [ ]:
a.T   #transpose of a matrix which interchanges the rows and coloumns.

array([[84, 49, 34],
       [18, 72,  7],
       [ 3, 61, 64]])

In [ ]:
#2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.
import numpy as np
a=np.random.randint(1,100 , size =10)

In [ ]:
a

array([89, 69, 28, 35,  7, 59, 45, 31,  1, 78])

In [ ]:
a.reshape(2,5)

array([[89, 69, 28, 35,  7],
       [59, 45, 31,  1, 78]])

In [ ]:
a.reshape(5,2)

array([[89, 69],
       [28, 35],
       [ 7, 59],
       [45, 31],
       [ 1, 78]])

In [ ]:
#3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.
import numpy as np
a=np.random.rand(4,4)
print(a)
b = np.zeros((6, 6))
# Place the original array in the center of the 6x6 array
b[1:5, 1:5] = a
print(b)

[[0.22389053 0.84027603 0.96439944 0.12182852]
 [0.42642526 0.51479227 0.31777492 0.70550963]
 [0.44641893 0.77715683 0.70832589 0.96221494]
 [0.29948718 0.91065415 0.58535678 0.31361112]]
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.22389053 0.84027603 0.96439944 0.12182852 0.        ]
 [0.         0.42642526 0.51479227 0.31777492 0.70550963 0.        ]
 [0.         0.44641893 0.77715683 0.70832589 0.96221494 0.        ]
 [0.         0.29948718 0.91065415 0.58535678 0.31361112 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [ ]:
#4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.
import numpy as np
arr=np.arange(10,60,5)
print(arr)

[10 15 20 25 30 35 40 45 50 55]


In [ ]:
 #5.Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.\
import numpy as np
a=np.array(['python', 'numpy', 'pandas'])
print(a)

['python' 'numpy' 'pandas']


In [ ]:
np.char.upper(a)

array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6')

In [ ]:
np.char.lower(a)

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [ ]:
np.char.title(a)

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

In [ ]:
#6. Generate a NumPy array of words. Insert a space between each character of every word in the array.
import numpy as np
a = np.array(['hello', 'world', 'numpy', 'array'])
b = np.array([' '.join([char for char in word]) for word in a])
print(b)

['h e l l o' 'w o r l d' 'n u m p y' 'a r r a y']


In [ ]:
#7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.
import numpy as np
a1=np.array([[1,2,3],[4,5,6]])
a2=np.array([[1,2,3],[4,5,6]])
c=a1+a2
d=a1-a2
e=a1*a2
f=a1/a2
print(c)
print(d)
print(e)
print(f)

[[ 2  4  6]
 [ 8 10 12]]
[[0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [16 25 36]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.
import numpy as np
a=np.eye(5)
print(a)
print(np.diag(a))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[1. 1. 1. 1. 1.]


In [ ]:
#9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.
import numpy as np
a=np.random.randint(0,1000,size=100)
print(a)
prime_numbers = []
for num in a:
    if num > 1:  # Check if the number is greater than 1
        is_prime = True
        for i in range(2, int(num**0.5) + 1):
            if num % i == 0:
                is_prime = False
                break
        if is_prime:
            prime_numbers.append(num)
            print(prime_numbers)

[424 197 206 880 234 761 250 417  24 240 663 842 659 603 389 275  28 187
 726 242 342 381 147 244 651 368 301 888 996 778 574 105 237   4  66 654
 230 343 101 890 914 418 670 913 273 835 708 927 665 959 443 675 478 380
 592 601 633 595 472 875  17 330 960  49 424 122 121 393 454 364 971 439
 436 582 753 526 633 737 314 758 325 989 881 477 854 656 261 309 285 507
 424 437 749 958 731 201 609 326  20 981]
[197]
[197, 761]
[197, 761, 659]
[197, 761, 659, 389]
[197, 761, 659, 389, 101]
[197, 761, 659, 389, 101, 443]
[197, 761, 659, 389, 101, 443, 601]
[197, 761, 659, 389, 101, 443, 601, 17]
[197, 761, 659, 389, 101, 443, 601, 17, 971]
[197, 761, 659, 389, 101, 443, 601, 17, 971, 439]
[197, 761, 659, 389, 101, 443, 601, 17, 971, 439, 881]


In [ ]:
#10.. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.
import numpy as np
a=np.random.randint(25,34,size=28)
print(a)
a.reshape(4,7).mean(axis=1)

[32 28 29 33 25 29 26 28 25 28 28 26 26 32 27 27 33 26 32 25 25 32 33 28
 28 30 31 27]


array([28.85714286, 27.57142857, 27.85714286, 29.85714286])